spring:
  datasource:
    url: jdbc:h2:tcp://MyH2Instance:1521/~./compTrxApi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
    MELT: debug
    org.hibernate.SQL: trace

server:
  port: 8080

const:
  url: "http://ec2-13-124-228-22.ap-northeast-2.compute.amazonaws.com"
  port-item: ":9100"
  port-bill: ":9200"