spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9093/~/compTrxApi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
    MELT: debug
    org.hibernate.SQL: trace

server:
  port: 9000